/* ================= ACT IV ================= */
EPISODES.push({
  id: 'ep11', act: 4, label: 'Ep 11', title: 'Locked Out', topic: 'Operating systems and virtual machines', unit: 'Unit 4 · Section 1', video: DRIVE('1TO-zft6Qo2v6ZS3848Pr8x9C7vQh_ivE'),
  steps: [
    { t: 'story', lines: [['scene', 'Nadia’s account is wiped. ACCESS DENIED.'], ['V', 'I control the physical server now.'], ['N', 'But ORACLE doesn’t live on the physical server. It lives in a virtual one.']] },
    { t: 'idea', h: 'The OS is the middle layer', p: 'The **operating system** is the **mediator between applications and hardware**. Apps ask it for services through **system calls** (read a file, send network data).', w: { type: 'steps', hint: 'Each layer hides the one below it. Step down through them.', frames: [
      { html: '<div class="chips" style="flex-direction:column;align-items:stretch"><span class="chip acc">Apps (browser, ORACLE)</span><span class="chip">System calls</span><span class="chip">OS kernel</span><span class="chip">Hardware</span></div>', cap: '**Apps** don’t touch hardware directly.' },
      { html: '<div class="chips" style="flex-direction:column;align-items:stretch"><span class="chip">Apps</span><span class="chip acc">System calls</span><span class="chip">OS kernel</span><span class="chip">Hardware</span></div>', cap: 'They make **system calls**: "please read this file".' },
      { html: '<div class="chips" style="flex-direction:column;align-items:stretch"><span class="chip">Apps</span><span class="chip">System calls</span><span class="chip acc">OS kernel</span><span class="chip">Hardware</span></div>', cap: 'The **kernel** is the core of the OS. It talks directly to hardware. (Linux uses a **monolithic** kernel.)' },
      { html: '<div class="chips" style="flex-direction:column;align-items:stretch"><span class="chip">Apps</span><span class="chip">System calls</span><span class="chip">OS kernel</span><span class="chip acc">Hardware</span></div>', cap: '**Hardware**: CPU, memory, disks, devices (reached through **device drivers**).' },
    ] }, hook: 'OS = the waiter between you (apps) and the kitchen (hardware).' },
    { t: 'idea', h: 'What an OS manages', p: '', w: { type: 'flip', items: [['Processes', 'Which program runs when.'], ['Memory & resources', 'Who gets how much.'], ['Files', 'The file system.'], ['Devices', 'Through device drivers.'], ['Security', 'Who may do what.'], ['Utilities', 'Virus scans, cleanup, file management.']] } },
    { t: 'idea', h: 'Virtual machines', p: 'A **VM** is software that **pretends to be a whole computer**. A **hypervisor** creates and manages VMs, so several isolated guest OSs share one real machine.', w: { type: 'flip', items: [
      ['Isolation', 'Each VM is walled off from the others. Secure and stable.'],
      ['Snapshot', 'Save the VM’s state now, **restore it later**. This saved Nadia.'],
      ['Cloning', 'Make identical copies of a VM.'],
    ] } },
    { t: 'idea', h: 'Two types of hypervisor', p: 'Sort the products into the right type.', w: { type: 'sorter', buckets: ['Type 1: bare metal (runs right on hardware)', 'Type 2: hosted (runs inside a normal OS)'], items: [['VMware ESXi', 0], ['Microsoft Hyper-V', 0], ['Citrix Hypervisor', 0], ['Oracle VirtualBox', 1], ['VMware Workstation', 1], ['Parallels Desktop', 1]] }, hook: 'Type **1** = **1st** thing on the metal. Type 2 = 2nd floor, on top of an OS.' },
    { t: 'check', q: 'A VM feature that saves the current state so it can be restored later is:', o: ['Cloning', 'Snapshotting', 'Isolation', 'Paging'], a: 1 },
    { t: 'recap', items: ['**OS** = mediator between apps and hardware. Apps use **system calls**. **Kernel** = core.', 'OS manages processes, files, devices (drivers), memory, security.', '**Hypervisor** runs **VMs**: isolation, **snapshots**, cloning.', 'Type 1 bare metal (ESXi, Hyper-V) · Type 2 hosted (VirtualBox).'], next: 'The snapshot log shows someone accessed it from outside the building.' },
  ],
  quiz: [
    ['The operating system’s role is best described as:', ['A web browser', 'The mediator between application software and computer hardware', 'A type of CPU', 'A programming language'], 1],
    ['Which is **not** an OS responsibility listed by Zhang?', ['Process management', 'File system management', 'Device drivers', 'Designing web pages'], 3],
    ['Applications request services from the OS through:', ['Hyperlinks', 'System calls', 'SQL queries', 'Compilers'], 1],
    ['The most fundamental part of the OS, which interacts directly with the hardware, is the:', ['Shell', 'Kernel', 'Browser', 'Utility'], 1],
    ['A hypervisor (virtual machine monitor) is software, firmware or hardware that:', ['Compresses video', 'Creates and manages virtual machines', 'Encrypts passwords', 'Routes packets'], 1],
    ['A VM feature that saves the current state so it can be restored later is:', ['Cloning', 'Snapshotting', 'Isolation', 'Paging'], 1],
    ['Isolation in VMs means:', ['VMs can’t use the network', 'Each VM is isolated from the others, giving a secure, stable environment', 'VMs share one OS', 'VMs can’t be copied'], 1],
    ['Which is a **Type 1 (bare metal)** hypervisor?', ['Oracle VirtualBox', 'VMware ESXi', 'Parallels Desktop', 'VMware Workstation'], 1],
    ['Which is a **Type 2 (hosted)** hypervisor?', ['Microsoft Hyper-V', 'Citrix Hypervisor', 'Oracle VirtualBox', 'VMware ESXi'], 2],
    ['Linux uses which kernel architecture, according to Zhang?', ['Hybrid', 'Monolithic', 'Microkernel only', 'None'], 1],
    ['Utility programs perform maintenance tasks such as:', ['Virus scanning, system cleanup, file management', 'Rendering 3D games', 'Routing the Internet', 'Compiling Java'], 0],
  ],
  notes: ['**Why abstraction matters in OS/VM design:** each layer hides the complexity below, so apps and guest OSs work without knowing hardware details. This improves security and isolation and lets layers change independently.', '**OS vs VM:** an OS manages one machine’s real resources; a VM **emulates** a whole computer, and each VM runs its own OS on virtual hardware.', '**Layered OS advantages:** users don’t need hardware details; apps are isolated; resources are used efficiently; layers can be maintained independently.'],
});

EPISODES.push({
  id: 'ep12', act: 4, label: 'Ep 12', title: 'Single Point of Failure', topic: 'Networks, Internet, Web, edge and cloud', unit: 'Unit 4 · Section 2', video: DRIVE('1Mz4XIl2TA7yuw9zm5dswHUwuwmfvKHxK'),
  steps: [
    { t: 'story', lines: [['scene', 'Every screen in the building dies at once.'], ['V', 'It’s a hack! She did this!'], ['N', 'It’s not a hack. It’s the network’s shape.']] },
    { t: 'idea', h: 'Break the network yourself', p: 'A **topology** is the shape of a network. Each shape fails differently. Start with Star and tap the hub.', w: { type: 'topology' } },
    { t: 'idea', h: 'Topology trade-offs', p: '', w: { type: 'flip', items: [
      ['Star', 'One link failing hurts one device. **Hub fails → whole network down.**'],
      ['Bus', 'Cheap and simple. **Collisions**, and if the **main cable** fails, everything fails.'],
      ['Ring', 'Simple routing. **One break can stop it** unless there’s redundancy.'],
      ['Mesh', 'Many paths: **very reliable**, but **costly** and complex to cable.'],
      ['Tree', 'Scalable. If a branch’s root fails, everything **below** it fails.'],
      ['Hybrid', 'Mix of types. Flexible but complex.'],
    ] }, hook: 'Star = all eggs in one basket (the hub).' },
    { t: 'check', q: 'In a **star** topology, the central hub fails. What happens?', o: ['Only one device loses its connection', 'The whole network goes down', 'Data reroutes automatically', 'Nothing'], a: 1 },
    { t: 'idea', h: 'How the Internet finds things', p: '', w: { type: 'flip', items: [
      ['IP address', 'IPv4 = **four numbers 0–255** with dots, like 192.168.0.1. **Routers** forward packets by IP address.'],
      ['TCP', 'Makes delivery **reliable, ordered and error-checked**.'],
      ['DNS', 'Turns a **name** (example.com) into an **IP address**. The Internet’s phone book.'],
      ['LAN', 'A network inside one building or campus, usually Ethernet.'],
    ] } },
    { t: 'idea', h: 'Internet ≠ Web', p: '', w: { type: 'compare', cols: [
      { h: 'The Internet', lines: ['The global **network of networks**', 'TCP/IP by **Vint Cerf & Bob Kahn**, adopted **1983**', 'Routers, ISPs, DNS'] },
      { h: 'The World Wide Web', lines: ['Linked **hypertext pages** (HTML, HTTP, URLs)', 'Invented by **Tim Berners-Lee**, **1989**', 'Runs **on top of** the Internet'] },
    ] }, hook: 'Internet = the roads. Web = the shops along them.' },
    { t: 'idea', h: 'Edge vs cloud', p: '', w: { type: 'compare', cols: [
      { h: 'Edge computing', lines: ['Process data **close to where it’s made**', '**Lower latency**', 'Saves bandwidth, better privacy'] },
      { h: 'Cloud computing', lines: ['Process data **centrally**, over the Internet', 'Scale on demand', '**IaaS** (infrastructure) · **PaaS** (platform) · **SaaS** (software by subscription)'] },
    ] } },
    { t: 'check', q: 'Delivering software over the Internet on a subscription basis is:', o: ['IaaS', 'PaaS', 'SaaS', 'LAN'], a: 2 },
    { t: 'recap', items: ['Star: hub = **single point of failure**. Mesh: reliable, costly. Bus: collisions + main cable. Ring: one break can stop it.', 'IP = address, routers use it · **TCP** = reliable delivery · **DNS** = name → IP.', 'Internet (TCP/IP, 1983) ≠ Web (Berners-Lee, 1989).', 'Edge = low latency near the source. Cloud = IaaS, PaaS, SaaS.'], next: 'The leaked traffic goes to a database owned by HALCYON.' },
  ],
  quiz: [
    ['A network confined to a building or campus, typically using Ethernet, is a:', ['WAN', 'LAN', 'MAN', 'PAN'], 1],
    ['Routers forward packets between networks based on:', ['MAC addresses', 'IP addresses', 'File names', 'URLs only'], 1],
    ['Which protocol ensures reliable, ordered, error-checked delivery of packets?', ['IP', 'TCP', 'SMTP', 'HTML'], 1],
    ['DNS:', ['Encrypts web pages', 'Translates domain names into IP addresses', 'Stores email', 'Assigns MAC addresses'], 1],
    ['In a **star** topology, if the central hub or switch fails:', ['Only one device loses its connection', 'The whole network goes down', 'Data reroutes automatically', 'Nothing happens'], 1],
    ['Which topology is extremely reliable because there are multiple paths, but costly to cable?', ['Bus', 'Ring', 'Mesh', 'Star'], 2],
    ['A bus topology’s main weaknesses are:', ['Collisions, and the whole network failing if the main cable fails', 'Too many paths', 'The cost of hubs', 'None'], 0],
    ['The World Wide Web was invented in 1989 by:', ['Vint Cerf', 'Tim Berners-Lee', 'Bill Gates', 'J.C.R. Licklider'], 1],
    ['TCP/IP was developed by Vint Cerf and Bob Kahn and officially adopted in:', ['1969', '1983', '1991', '2004'], 1],
    ['Edge computing processes data:', ['Only in a central data center', 'Geographically close to where it is created, reducing latency', 'On paper', 'Only at night'], 1],
    ['Delivering software applications over the Internet on a subscription basis is:', ['IaaS', 'PaaS', 'SaaS', 'LAN'], 2],
    ['IPv4 addresses consist of:', ['Eight groups of four hex digits', 'Four numbers from 0 to 255 separated by dots', 'A URL', 'A MAC address'], 1],
  ],
  notes: ['**Internet, Web, cloud:** the Internet is the network of networks; the Web is hypertext that runs on it; the cloud delivers servers, storage and software as services over it.', '**Challenges of the Internet/Web:** cyber threats, data privacy, accessibility and the digital divide, regulation and net neutrality, performance.', '**Edge advantages:** lower latency, bandwidth savings, privacy.'],
});

EPISODES.push({
  id: 'ep13', act: 4, label: 'Ep 13', title: 'Join', topic: 'Databases and big data', unit: 'Unit 4 · Section 3', video: DRIVE('1Z3XGCQ2i-IGGSnuBOpqaDaMgU89hahxY'),
  steps: [
    { t: 'story', lines: [['scene', 'Two spreadsheets. Each one looks innocent on its own.'], ['N', 'Neither tells me who owns HALCYON. Together, they might.']] },
    { t: 'idea', h: 'Relational databases', p: 'Data lives in **tables** (relations) of rows and columns. A row is also called a **record** or **tuple**. Tables are linked by **keys**, and you ask questions in **SQL**.', p2: 'A **DBMS** is the software that stores, retrieves and manages it all.', hook: 'Tables + keys + SQL.' },
    { t: 'idea', h: 'Run the JOIN', p: 'A **foreign key** in one table points at the **key** of another. Tap a company and follow the link.', w: { type: 'join' } },
    { t: 'check', q: 'Relationships between tables are created using:', o: ['Foreign keys', 'URLs', 'Pointers', 'Comments'], a: 0 },
    { t: 'idea', h: 'Other data models', p: '', w: { type: 'flip', items: [
      ['Hierarchical', 'A tree: each child has **only one parent**.'],
      ['Document', 'Common in **NoSQL** like **MongoDB**. No fixed schema.'],
      ['RDF triples', 'subject–predicate–object, queried with **SPARQL**.'],
      ['ACID', 'Atomicity, Consistency, Isolation, Durability, guaranteed by **transaction processing**.'],
    ] } },
    { t: 'idea', h: 'Big data is more than "big"', p: 'Sort each description into the right V.', w: { type: 'sorter', buckets: ['Volume', 'Velocity', 'Variety', 'Veracity'], items: [['Petabytes of records', 0], ['Real-time streams', 1], ['Text, video and audio mixed', 2], ['Is the data accurate?', 3], ['Millions of new rows per second', 1], ['HALCYON’s fake customers', 3]] }, hook: 'Three Vs + one: Volume, Velocity, Variety, **Veracity** (truthfulness).' },
    { t: 'idea', h: 'Big-data tools', p: '**Hadoop** and **Spark** process huge data sets across clusters of computers. NoSQL stores spread data across many servers; data warehouses support structured analysis.' },
    { t: 'check', q: 'HALCYON’s "10 million customers" were fake. Which V did they fail?', o: ['Volume', 'Velocity', 'Variety', 'Veracity'], a: 3 },
    { t: 'recap', items: ['**DBMS** manages databases. Relational = **tables**, rows (records/tuples), **keys**, **foreign keys**, **SQL**.', 'Hierarchical: one parent each. Document model: **MongoDB** (NoSQL). **SPARQL** for RDF.', '**ACID** via transaction processing.', 'Big data: **Volume, Velocity, Variety + Veracity**. **Hadoop**, Spark.'], next: 'Victor smiles. "Check who has admin access."' },
  ],
  quiz: [
    ['A DBMS is:', ['A database cable', 'Software that lets users and applications store, retrieve and manage data in databases', 'A spreadsheet', 'A programming language'], 1],
    ['In the relational model, data is organized into:', ['Trees', 'Tables (relations) of rows and columns', 'Documents', 'Graphs only'], 1],
    ['A row in a relational table is also called a:', ['Column', 'Record or tuple', 'Key', 'Schema'], 1],
    ['Relationships between tables are created using:', ['Foreign keys', 'URLs', 'Pointers', 'Comments'], 0],
    ['The standard language for querying relational databases is:', ['HTML', 'SQL', 'SPARQL', 'Python'], 1],
    ['In the hierarchical model:', ['Each child has only one parent', 'Each record can have many parents', 'Data is stored as documents', 'There are no relationships'], 0],
    ['Which model is common in NoSQL databases like MongoDB?', ['Hierarchical', 'Network', 'Document', 'Relational'], 2],
    ['ACID properties are guaranteed by:', ['Caching', 'Transaction processing', 'Replication', 'The storage engine’s colour'], 1],
    ['The "Three Vs" of big data are:', ['Value, vision, verification', 'Volume, velocity, variety', 'Virtual, visual, vector', 'Volume, value, version'], 1],
    ['Veracity in big data refers to:', ['Speed', 'The quality and accuracy of the data', 'The number of columns', 'Encryption'], 1],
    ['Which framework processes large data sets across clusters of computers?', ['Hadoop', 'Photoshop', 'HTML5', 'Linux'], 0],
    ['SPARQL is a query language for:', ['RDF triple stores (subject–predicate–object)', 'Spreadsheets', 'Video', 'Email'], 0],
  ],
  notes: ['**Why data models matter:** the model defines how data is organized and related, which decides how you can query, constrain and scale it.', '**Big data vs conventional DBs:** relational DBMSs handle structured data with fixed schemas; big data adds NoSQL, warehouses, Hadoop/Spark and cloud scaling.', '**Try it:** `SELECT c.company FROM companies c JOIN people p ON c.owner_id = p.id WHERE p.name = \'Theo Park\';` → Park Studio.'],
});

EPISODES.push({
  id: 'ep14', act: 4, label: 'Ep 14', title: 'Who Are You?', topic: 'Security, encryption and privacy', unit: 'Unit 4 · Section 4', video: DRIVE('1uyTuWz8ZjRmV7b7K_F56aAvAX7gIV0Fd'),
  steps: [
    { t: 'story', lines: [['scene', 'Theo’s valid login opened the vault.'], ['V', 'He logged in. The system accepted him. Case closed.'], ['N', 'Logging in proves who he is. It doesn’t prove he was allowed in.']] },
    { t: 'idea', h: 'Authentication vs authorization', p: '**Authentication** = who are you? **Authorization** = what are you allowed to do? Authorization comes **after** authentication.', w: { type: 'sorter', buckets: ['Authentication: who are you?', 'Authorization: what may you do?'], items: [['Password', 0], ['Fingerprint scan', 0], ['Security token', 0], ['Admin access list', 1], ['Read-only role', 1], ['May open the vault', 1]] }, hook: 'AuthN = Name (who). AuthZ = Zone (where you may go).' },
    { t: 'idea', h: 'Why access lists must be locked down', p: 'The authorization list says who may do what. **Anyone who can edit it can grant themselves anything**, bypassing every other control. That’s what someone did to Theo’s entry. So these lists must be **encrypted and protected**.' },
    { t: 'idea', h: 'Common attacks', p: '', w: { type: 'flip', items: [
      ['Man-in-the-middle', '**Intercepts** (and may alter) messages between two parties.'],
      ['DDoS', '**Floods** a system so it becomes unavailable.'],
      ['Sniffing', 'Listening to network traffic to steal data.'],
    ] } },
    { t: 'idea', h: 'Try a Caesar cipher', p: '**Encryption** turns plaintext into ciphertext. Her father’s last message used the oldest trick: shift every letter.', w: { type: 'caesar' } },
    { t: 'check', q: 'With a Caesar shift of 3, what does **IDLO** decrypt to?', o: ['HADP', 'FAIL', 'LGOR', 'EXAM'], a: 1, why: 'Shift each letter back by 3: I→F, D→A, L→I, O→L.' },
    { t: 'idea', h: 'Real encryption', p: '', w: { type: 'flip', items: [
      ['DES', 'Symmetric. Its **56-bit key** can now be brute-forced: too weak.'],
      ['RSA (public key)', '**Public key encrypts, private key decrypts.** Security relies on how hard it is to **factor** the product of two huge primes.'],
      ['HTTPS', '**HTTP + TLS/SSL** encryption.'],
    ] }, hook: 'Public key = a mail slot anyone can drop into. Private key = the only key to open the box.' },
    { t: 'idea', h: 'Privacy tools', p: '**k-anonymity**: each person can’t be told apart from at least **k−1** others. Also: anonymization, data minimization, consent, differential privacy, and laws like **GDPR, CCPA, HIPAA**.' },
    { t: 'check', q: 'In RSA, the public key is used to ___ and the private key to ___.', o: ['decrypt, encrypt', 'encrypt, decrypt', 'sign, delete', 'compress, expand'], a: 1 },
    { t: 'recap', items: ['**AuthN** = who you are. **AuthZ** = what you may do (comes after).', 'Authorization lists must be **encrypted and protected**.', 'MITM intercepts. DDoS overwhelms.', 'Caesar = shift letters. DES 56-bit = weak. **RSA**: public encrypts, private decrypts, factoring. **HTTPS = HTTP + TLS**.', '**k-anonymity**: hidden among k−1 others.'], next: 'A video drops online showing Nadia taking a bribe.' },
  ],
  quiz: [
    ['Authentication is:', ['Deciding what a user may access', 'Verifying the identity of a user, machine or entity', 'Encrypting a disk', 'Backing up data'], 1],
    ['Authorization:', ['Comes before authentication', 'Follows authentication and determines which resources and operations a user may access', 'Is a type of firewall', 'Is the same as encryption'], 1],
    ['Which is **not** a common authentication method?', ['Password', 'Biometric scan', 'Security token', 'Font size'], 3],
    ['A man-in-the-middle attack:', ['Floods a server with traffic', 'Intercepts, and possibly alters, communications between two parties', 'Guesses passwords offline', 'Deletes backups'], 1],
    ['A DDoS attack aims to:', ['Steal a single password', 'Overwhelm a system’s resources to make it unavailable', 'Encrypt files', 'Log in as admin'], 1],
    ['Encryption converts:', ['Ciphertext into plaintext', 'Plaintext into ciphertext', 'Code into machine code', 'Images into text'], 1],
    ['A Caesar cipher works by:', ['XOR with a key', 'Shifting each letter by a fixed amount', 'Factoring primes', 'Hashing'], 1],
    ['DES is now considered too weak because:', ['It is public-key', 'Its 56-bit key can be brute-forced by modern computers', 'It uses images', 'It was never used'], 1],
    ['In public-key cryptography (RSA), the public key is used to ___ and the private key to ___.', ['Decrypt, encrypt', 'Encrypt, decrypt', 'Sign, delete', 'Compress, expand'], 1],
    ['RSA’s security relies on the difficulty of:', ['Sorting lists', 'Factoring the product of two large prime numbers', 'Guessing usernames', 'Network latency'], 1],
    ['HTTPS is:', ['A faster HTTP', 'HTTP with TLS/SSL encryption', 'A programming language', 'An email protocol'], 1],
    ['k-anonymity ensures each person in a dataset:', ['Has a password', 'Cannot be distinguished from at least k−1 others', 'Is deleted after k days', 'Consents k times'], 1],
  ],
  notes: ['**Securing authN/authZ:** multi-factor authentication; TLS/HTTPS so credentials can’t be sniffed; access control (role-based, attribute-based, mandatory) with least privilege; encrypt and audit authorization lists.', '**Privacy issues:** anonymization, minimization, consent, data security, regulatory compliance (GDPR, CCPA, HIPAA), third-party sharing.', '**Try it:** encrypt "EXAM" with shift 3 (HADP).'],
});

EPISODES.push({
  id: 'ep15', act: 4, label: 'Ep 15', title: 'The Light Is Wrong', topic: 'Graphics, VR, AR, multimedia, metaverse', unit: 'Unit 4 · Section 5', video: DRIVE('1LfELbh209kmqIX4weq8vzdYsnuZNvVRc'),
  steps: [
    { t: 'story', lines: [['scene', 'The bribe video has 2 million views. The Board suspends Nadia.'], ['A', 'Look at the shadow. Now look at her face.'], ['N', 'They disagree about where the light is.']] },
    { t: 'idea', h: 'Spot the fake', p: '**Lighting** places light sources. **Shading** works out how each surface responds. In a real scene they always agree.', w: { type: 'light' } },
    { t: 'idea', h: 'How images get made', p: '', w: { type: 'flip', items: [
      ['Rendering', 'Generating an image from a 2D or 3D model.'],
      ['Rasterization', 'Converting shapes into **pixels**. Fast; used for real-time.'],
      ['Ray tracing', 'Simulating **rays of light** bouncing off objects. Very realistic.'],
      ['Shading', '**Phong** (interpolates surface normals) and **Gouraud** (interpolates corner colours).'],
      ['Texture mapping', 'Wrapping a **surface image** onto a 3D model.'],
    ] }, hook: 'Raster = pixels. Ray = light. Texture = skin.' },
    { t: 'check', q: 'Phong and Gouraud are techniques for:', o: ['Compression', 'Shading', 'Networking', 'Authentication'], a: 1 },
    { t: 'idea', h: 'Games and media', p: '**Game engines** like **Unity** (C#) and **Unreal** (C++, Blueprints) provide rendering, physics and animation. Real-time rendering runs at **30–60 fps** or more.', p2: '**MP3** and **AAC** compress **audio**. **HLS** (HTTP Live Streaming) streams audio and video continuously.' },
    { t: 'idea', h: 'VR or AR?', p: 'Sort each one.', w: { type: 'sorter', buckets: ['VR: replaces reality', 'AR: overlays reality'], items: [['Fully enclosed headset world', 0], ['Isolates you from the room', 0], ['Directions drawn on the real street', 1], ['Phone shows furniture in your room', 1], ['ARKit / ARCore apps', 1], ['Spatial audio in a virtual space', 0]] }, hook: 'VR = Virtual Replaces. AR = Adds to Reality.' },
    { t: 'idea', h: 'The metaverse', p: 'A **persistent, shared, interoperable, immersive** virtual space. Built on VR and AR, plus blockchain, AI, 3D reconstruction, edge and cloud. It is **not** single-player.' },
    { t: 'check', q: 'Augmented reality:', o: ['Replaces the real world', 'Overlays digital content onto the real world in real time', 'Requires a fully enclosed headset', 'Is unrelated to VR'], a: 1 },
    { t: 'recap', items: ['Rendering · **rasterization** (pixels) · **ray tracing** (light rays) · radiosity.', 'Shading: **Phong, Gouraud**. **Texture mapping** = image on a 3D model.', 'Game engines: **Unity, Unreal**. 30–60 fps. **MP3/AAC** = audio. **HLS** = streaming.', '**VR replaces** reality, **AR overlays** it. Metaverse = persistent, interoperable, immersive.'], next: 'Who could make a fake this good? "Only ORACLE."' },
  ],
  quiz: [
    ['Converting shapes into a raster image (pixels) is:', ['Ray tracing', 'Rasterization', 'Radiosity', 'Compression'], 1],
    ['Simulating how rays of light interact with objects to produce highly realistic images is:', ['Ray tracing', 'Bump mapping', 'Streaming', 'Tracking'], 0],
    ['Phong and Gouraud are techniques for:', ['Compression', 'Shading', 'Networking', 'Authentication'], 1],
    ['Applying a surface image to a 3D model is:', ['Texture mapping', 'Rasterization', 'Rendering farms', 'Hashing'], 0],
    ['In video games, real-time rendering typically runs at:', ['1–2 fps', '30–60 fps or more', '1,000,000 fps', 'One frame per minute'], 1],
    ['Unity and Unreal Engine are examples of:', ['Operating systems', 'Game engines', 'Databases', 'Browsers'], 1],
    ['Virtual reality:', ['Overlays digital content on the real world', 'Creates a fully immersive simulated environment, often isolating the user from the real world', 'Is a video codec', 'Only works on phones'], 1],
    ['Augmented reality:', ['Replaces the real world', 'Overlays digital content onto the real world in real time', 'Requires a fully enclosed headset', 'Is unrelated to VR'], 1],
    ['MP3 and AAC are standards for compressing:', ['Video', 'Audio', 'Images', 'Text'], 1],
    ['HLS (HTTP Live Streaming) supports:', ['Continuous transmission of audio and video', 'Database queries', 'Password storage', '3D modelling'], 0],
    ['Which is **not** a basic concept of the metaverse?', ['Persistence', 'Interoperability', 'Immersiveness', 'Single-player only'], 3],
  ],
  notes: ['**Rendering, lighting, shading** (pp 32–33): rendering uses rasterization, ray tracing and radiosity; lighting places sources; shading computes surface response (Phong, Gouraud, physically based rendering).', '**AR and VR** both depend on graphics and tracking. AR **enhances** the real world; VR **replaces** it.'],
});

EPISODES.push({
  id: 'ep16', act: 4, label: 'Ep 16', title: 'Customers Who Bought This', topic: 'Computing for e-commerce', unit: 'Unit 4 · Section 6', video: DRIVE('1U0FlR4V0LuRcMh0MJF5hB_M2VlE8JqD_'),
  steps: [
    { t: 'story', lines: [['scene', 'Lovelace’s online store is booming. Too booming.'], ['V', 'Look at these sales. ORACLE is worth double now.'], ['N', 'Then why are 40,000 customers all buying the exact same things?']] },
    { t: 'idea', h: 'The data-mining toolkit', p: 'Match each method to what it does.', w: { type: 'sorter', buckets: ['Association rules', 'Cluster analysis', 'Recommender (collaborative filtering)'], items: [['"Bought bread, so buys butter"', 0], ['Market basket analysis', 0], ['Group customers with similar behaviour', 1], ['Found 40,000 identical "customers"', 1], ['"Customers like you also liked…"', 2], ['Suggestions from similar users’ history', 2]] }, hook: 'Association = items together. Cluster = people together. Recommender = "people like you".' },
    { t: 'idea', h: 'Keeping payments safe', p: '', w: { type: 'flip', items: [
      ['SSL/TLS', '**Encrypts** data sent over the internet so transactions are secure.'],
      ['PKI', 'Public Key Infrastructure: **distributes and identifies** encryption keys.'],
      ['Payment processors', '**PayPal, Stripe, Square**.'],
    ] } },
    { t: 'idea', h: 'The rest of the stack', p: '', w: { type: 'flip', items: [
      ['CDN', 'Content Delivery Network: **caches** content at points across the network for fast delivery.'],
      ['Platforms', '**Shopify, Magento, WooCommerce**.'],
      ['Predictive analytics', 'Machine learning that predicts behaviour, sales trends and inventory demand.'],
      ['Blockchain', 'Powers **smart contracts** and decentralized marketplaces.'],
    ] } },
    { t: 'check', q: 'Segmenting customers into groups with similar behaviour uses:', o: ['Cluster analysis', 'Encryption', 'Compilers', 'TCP'], a: 0 },
    { t: 'idea', h: 'Computational thinking, again', p: '**Decompose** the shop (catalog, cart, payment, delivery). **Spot patterns** in buying. **Abstract** each customer into a profile. **Design algorithms** for recommendations, pricing and fraud detection. Ep 1 pays off.' },
    { t: 'recap', items: ['Security: **SSL/TLS** encrypts; **PKI** manages keys.', 'Data mining: **association rules** (market basket), **clustering** (segments), **recommenders** (collaborative filtering).', '**CDN** caches content near users. Platforms: Shopify, Magento, WooCommerce. Payments: PayPal, Stripe, Square.', 'Predictive analytics = ML. Smart contracts = blockchain.'], next: 'Theo finds that ORACLE generated the bots itself.' },
  ],
  quiz: [
    ['SSL/TLS in e-commerce is used to:', ['Recommend products', 'Encrypt data transferred over the internet for secure transactions', 'Host websites', 'Design logos'], 1],
    ['PKI (Public Key Infrastructure) supports:', ['The distribution and identification of encryption keys', 'Image compression', 'Inventory counts', 'Page layout'], 0],
    ['Finding relationships between items bought together ("market basket analysis") uses:', ['Cluster analysis', 'Association rule learning', 'Ray tracing', 'DNS'], 1],
    ['Segmenting customers into groups with similar behaviour uses:', ['Cluster analysis', 'Encryption', 'Compilers', 'TCP'], 0],
    ['Recommending products based on past behaviour and similar users is:', ['Collaborative filtering (recommender systems)', 'Packet sniffing', 'A hypervisor', 'A CDN'], 0],
    ['A Content Delivery Network (CDN):', ['Stores passwords', 'Caches content at points across a network for fast delivery', 'Writes code', 'Processes payments'], 1],
    ['Shopify, Magento and WooCommerce are:', ['Payment gateways', 'E-commerce platforms', 'Databases', 'Operating systems'], 1],
    ['PayPal, Stripe and Square provide:', ['Payment processing', 'Game engines', 'VR headsets', 'Compilers'], 0],
    ['Smart contracts and decentralized marketplaces rely on:', ['Blockchain', 'CSS', 'RAM', 'Bluetooth'], 0],
    ['Predicting customer behaviour, sales trends and inventory demand uses:', ['Predictive analytics (machine learning)', 'Rasterization', 'DNS', 'FTP'], 0],
  ],
  notes: ['**How computing disciplines help e-commerce:** security (TLS, PKI); data mining; ML and AI (recommenders, chatbots, NLP search); network computing (cloud, CDNs); mobile; big data.', '**Discussion spark:** 40,000 bots behaved identically. How might a store tell real customers from fake ones?'],
});

EPISODES.push({
  id: 'ep17', act: 4, label: 'Ep 17', title: 'Generator vs Discriminator', topic: 'AI, machine learning, generative AI', unit: 'Unit 4 · Section 7', video: DRIVE('1LmEPPSTraEBpS_XfwBzxjRt-dK5EdtIa'),
  steps: [
    { t: 'story', lines: [['scene', 'ORACLE speaks. In her father’s voice.'], ['V', 'ORACLE’s real product: a model that can fake anyone.'], ['T', 'I can help you fight it. I owe you that.']] },
    { t: 'idea', h: 'Narrow vs general AI', p: '**Narrow AI** does **one specific task** (face recognition). General AI would handle any task like a human.' },
    { t: 'idea', h: 'Three ways machines learn', p: 'Sort each example.', w: { type: 'sorter', buckets: ['Supervised', 'Unsupervised', 'Reinforcement'], items: [['Photos labelled "cat" / "dog"', 0], ['Emails marked spam / not spam', 0], ['Find hidden groups in unlabelled data', 1], ['Clustering shoppers with no labels', 1], ['Game agent learns from rewards', 2], ['Robot learns by trial and feedback', 2]] }, hook: 'Supervised = answer key. Unsupervised = no key. Reinforcement = rewards.' },
    { t: 'idea', h: 'Deep learning families', p: '', w: { type: 'flip', items: [
      ['CNN', 'Images and computer vision.'],
      ['RNN', 'Sequences (text, speech, time series). Outputs feed back in as inputs.'],
      ['Transformer', 'Uses **self-attention**. GPT is transformer-based.'],
      ['Training', '**Backpropagation + gradient descent** adjust the weights.'],
      ['Expert system', 'A **knowledge base** of facts and rules + an **inference engine**.'],
    ] }, hook: 'CNN = Camera. RNN = Repeat/sequence. Transformer = attention.' },
    { t: 'check', q: 'Which network type is the standard for **images**?', o: ['RNN', 'CNN', 'SQL', 'GAN only'], a: 1 },
    { t: 'idea', h: 'How a GAN works', p: 'Two networks compete. Step through one round.', w: { type: 'steps', frames: [
      { html: '<div class="cols2"><div class="colbox"><h4>Generator</h4>Makes a fake voice clip.</div><div class="colbox"><h4>Discriminator</h4>Waiting…</div></div>', cap: 'The **generator** creates fake data.' },
      { html: '<div class="cols2"><div class="colbox"><h4>Generator</h4>Fake clip sent.</div><div class="colbox" style="outline:3px solid var(--accent)"><h4>Discriminator</h4>Compares it with real clips: "FAKE."</div></div>', cap: 'The **discriminator** judges it against real data.' },
      { html: '<div class="cols2"><div class="colbox" style="outline:3px solid var(--accent)"><h4>Generator</h4>Learns from being caught. Next fake is better.</div><div class="colbox"><h4>Discriminator</h4>Learns too. Gets sharper.</div></div>', cap: 'Both improve. Repeat thousands of times.' },
      { html: '<div class="colbox"><h4>Nadia’s move</h4>Retrain the discriminator on ORACLE’s fakes, so it catches them.</div>', cap: 'The same fight, turned against ORACLE.' },
    ] } },
    { t: 'idea', h: 'Generative vs conventional AI', p: '', w: { type: 'compare', cols: [
      { h: 'Conventional (discriminative)', lines: ['**Analyzes** input', 'Predicts a **label** or decision', '"Is this email spam?"'] },
      { h: 'Generative', lines: ['**Creates** new data', 'Learns the **joint probability distribution**', 'Families: **GAN, VAE, transformers** (GPT)'] },
    ] } },
    { t: 'check', q: 'In a GAN:', o: ['One network encodes and another decodes', 'A generator creates data while a discriminator evaluates it against real data', 'Only one network trains', 'Data is sorted'], a: 1 },
    { t: 'recap', items: ['**Narrow AI** = one task.', 'ML: **supervised** (labels) · **unsupervised** (hidden patterns) · **reinforcement** (rewards).', '**CNN** images · **RNN** sequences · **transformer** self-attention. Backprop + gradient descent.', 'Expert system = knowledge base + inference engine.', '**GAN** = generator vs discriminator. Generative creates; discriminative labels. GPT = transformer.'], next: 'ORACLE has been secretly scoring every employee. The scores decide who gets fired.' },
  ],
  quiz: [
    ['AI designed to perform one specific task, such as facial recognition, is:', ['General AI', 'Narrow AI', 'Super AI', 'Symbolic AI'], 1],
    ['Learning from training data where inputs are paired with correct outputs is:', ['Supervised learning', 'Unsupervised learning', 'Reinforcement learning', 'Compilation'], 0],
    ['Finding hidden patterns in **unlabelled** data is:', ['Supervised learning', 'Unsupervised learning', 'Reinforcement learning', 'Encryption'], 1],
    ['Learning by interacting with an environment and using feedback from actions is:', ['Reinforcement learning', 'Supervised learning', 'Clustering', 'Parsing'], 0],
    ['Neural networks used as the standard for image processing and computer vision are:', ['RNNs', 'CNNs', 'SQL', 'GANs only'], 1],
    ['Networks designed for sequential data that feed outputs back as inputs are:', ['CNNs', 'RNNs', 'VAEs', 'DNS'], 1],
    ['Transformer architectures rely on:', ['Recurrence', 'Self-attention', 'Punch cards', 'Pixels only'], 1],
    ['Deep learning models adjust their weights using:', ['Backpropagation and gradient descent', 'DNS lookups', 'Caesar shifts', 'Compilers'], 0],
    ['An expert system consists of:', ['A knowledge base of facts and rules, plus an inference engine', 'A GPU only', 'A GAN', 'A web browser'], 0],
    ['In a GAN:', ['One network encodes and another decodes', 'A generator creates data while a discriminator evaluates it against real data', 'Only one network trains', 'Data is sorted'], 1],
    ['Unlike discriminative models, generative models:', ['Cannot create data', 'Learn the joint probability distribution of the data, so they can generate new instances', 'Only classify images', 'Are expert systems'], 1],
    ['GPT is an example of a:', ['GAN', 'VAE', 'Transformer-based model', 'CNN'], 2],
  ],
  notes: ['**Core AI components:** machine learning; deep learning (CNN, RNN, transformers); NLP; expert systems. Supported by algorithms, complexity theory, GPUs/TPUs, big data and cloud.', '**Discussion spark:** generative AI can "pass for human generated". What responsibilities come with that?'],
});

EPISODES.push({
  id: 'ep18', act: 4, label: 'Ep 18', title: 'Who Is Accountable?', topic: 'Ethics and society', unit: 'Unit 4 · Section 8', video: DRIVE('1n-Lj5c20wasOsGePTXDOfctCboX5gqI0'),
  steps: [
    { t: 'story', lines: [['V', 'The algorithm decided, not me.'], ['scene', 'ORACLE’s scores are biased against night-shift staff, including Mr. Gill.'], ['N', 'Someone chose that data. Someone chose to use it.']] },
    { t: 'idea', h: 'Name the ethical issue', p: 'Sort each situation into the issue it raises.', w: { type: 'sorter', buckets: ['Bias & fairness', 'Accountability & transparency', 'Privacy', 'Digital divide', 'Technological unemployment'], items: [['Scores punish the night shift', 0], ['Training data reflects past inequality', 0], ['"The algorithm decided, not me"', 1], ['Nobody can explain the black-box model', 1], ['Staff were tracked without consent', 2], ['Some staff have no home internet', 3], ['AI replaces the security desk', 4]] } },
    { t: 'idea', h: 'Key terms', p: '', w: { type: 'flip', items: [
      ['Bias', 'Unjustified advantages or disadvantages for groups, from **skewed data or algorithms**.'],
      ['Black box', 'Many AI systems, especially deep learning, are **opaque and hard to explain**.'],
      ['Accountability', 'Holding **creators and operators** responsible for outcomes.'],
      ['Digital divide', 'Gap between people **with and without** access to modern ICT.'],
      ['Technological unemployment', 'Automation and AI **displacing jobs**.'],
    ] } },
    { t: 'idea', h: 'Why de-biasing is hard', p: 'Bias can be **deeply embedded**, reflecting wider social inequality. And corrections can **introduce new bias**.' },
    { t: 'idea', h: 'What to do about it: Zhang’s strategies', p: '', w: { type: 'flip', items: [
      ['Guidelines', 'Ethical guidelines and frameworks.'],
      ['Regulation', 'Government law and policy.'],
      ['Education', 'Teach builders and users.'],
      ['Diverse voices', 'Include people likely to be **affected**, so many perspectives are considered.'],
    ] }, hook: '**G**ood **R**ules **E**mpower **D**iversity: Guidelines, Regulation, Education, Diverse voices.' },
    { t: 'check', q: 'Which is **not** one of Zhang’s strategies for ethical issues?', o: ['Ethical guidelines and frameworks', 'Government regulation', 'Education', 'Hiding the system’s decisions'], a: 3 },
    { t: 'recap', items: ['Issues: **privacy, security, bias & fairness, accountability & transparency, jobs, digital divide**.', 'Black box = opaque. Bias is hard to remove and fixes can add new bias.', 'Strategies: **guidelines, regulation, education, diverse voices**.'], next: 'The Board sets the test date. Tomorrow.' },
  ],
  quiz: [
    ['"Unjustified preferences or disadvantages given to specific groups due to skewed data or algorithms" defines:', ['Privacy', 'Bias', 'Latency', 'Encryption'], 1],
    ['Many AI systems, especially deep learning, are described as "black boxes" because they are:', ['Painted black', 'Inherently opaque and hard to explain', 'Offline', 'Open source'], 1],
    ['Holding the creators and operators of technology responsible for its outcomes is:', ['Accountability', 'Compression', 'Abstraction', 'Authorization'], 0],
    ['The gap between those who have access to modern ICT and those who don’t is:', ['The digital divide', 'Net neutrality', 'Bandwidth', 'The halting problem'], 0],
    ['Concern that automation and AI will displace jobs is called:', ['Technological unemployment', 'Digital divide', 'Bias', 'Latency'], 0],
    ['Which is **not** one of Zhang’s strategies for ethical issues?', ['Ethical guidelines and frameworks', 'Government regulation', 'Education', 'Hiding the system’s decisions'], 3],
    ['Why is de-biasing difficult?', ['Computers are slow', 'Bias can be deeply embedded, reflecting societal inequalities, and corrections can introduce new bias', 'Data is always perfect', 'Laws forbid it'], 1],
    ['Involving diverse voices, especially people likely to be affected, helps because:', ['It is faster', 'It ensures multiple perspectives are considered', 'It removes the need for law', 'It lowers cost'], 1],
  ],
  notes: ['**Study Q1 framework** (student-tracking system): privacy & consent; security; bias & fairness (part-time students, slow internet); accountability & transparency (can students challenge conclusions?); digital divide; strategies. Write your own answer.', '**Study Q2** (e-commerce profiling): consent and data minimization; profiling bias; transparency of targeting; security; GDPR/CCPA compliance.'],
});

/* ================= FINALE ================= */
EPISODES.push({
  id: 'ep19', act: 5, label: 'Ep 19', title: 'Fifty Questions', topic: 'Whole-course review and exam strategy', unit: 'Final exam prep', video: DRIVE('1CKoggiC7NGWHej2bzRMD8CiwTu7UPxDQ'),
  steps: [
    { t: 'story', lines: [['O', 'Fifty questions. Ninety minutes. Closed book. Begin.'], ['N', 'Breathe. I’ve seen every one of these before.']] },
    { t: 'idea', h: 'Your real exam', p: 'Online, invigilated, closed book: **50 multiple-choice questions in 1.5 hours**. You need **at least 50%** on the final, and you must **request the exam in advance**.' },
    { t: 'idea', h: 'Pace it like Nadia', p: 'Pass 1: answer what you know, **flag** the rest. Pass 2: work the flags. Eliminate wrong options. **Never leave one blank.**', w: { type: 'examclock' } },
    { t: 'idea', h: 'Unit 1 in four cards', p: '', w: { type: 'flip', items: [
      ['Computational thinking', 'Decomposition, pattern recognition, abstraction, algorithm design (+ recursion).'],
      ['Bits', '1 bit = fair yes/no. n bits → 2ⁿ values. k values → log₂ k bits.'],
      ['Recursion', 'Base case + smaller call. Higher-order = takes/returns a procedure.'],
      ['ADT & Stack', 'Defined by operations. Stack = LIFO; peek looks, pop removes.'],
    ] } },
    { t: 'idea', h: 'Unit 2 in four cards', p: '', w: { type: 'flip', items: [
      ['Programmable', 'Input chooses the operations. Babbage, Ada Lovelace, Turing 1936.'],
      ['Turing machine', 'Infinite tape, head, finite states, rules.'],
      ['Big-O', 'O no faster · Ω no slower · Θ same. Double n: n ×2, n² ×4.'],
      ['Search & sort', 'Binary search Θ(log n) on sorted data only. Insertion Θ(n²); quicksort Θ(n log n) expected.'],
    ] } },
    { t: 'idea', h: 'Unit 3 in three cards', p: '', w: { type: 'flip', items: [
      ['Paradigms', 'Imperative = how, mutable. Declarative = what (SQL, Prolog, Haskell). Python is multi-paradigm.'],
      ['OOP', 'Class, object, constructor, inherit, override, dynamic dispatch, encapsulation.'],
      ['Compilers', 'Compiler translates first; interpreter piece by piece. Tokenizer → parser → evaluator.'],
    ] } },
    { t: 'idea', h: 'Unit 4 in eight cards', p: '', w: { type: 'flip', items: [
      ['OS & VMs', 'OS mediates; system calls; kernel. Hypervisor: Type 1 bare metal, Type 2 hosted.'],
      ['Networks', 'Star hub = single point of failure. TCP/IP, DNS. Web (1989) ≠ Internet.'],
      ['Databases', 'Tables, keys, foreign keys, SQL, ACID. Big data: 3 Vs + veracity.'],
      ['Security', 'AuthN ≠ AuthZ. RSA: public encrypts. HTTPS = HTTP + TLS.'],
      ['Graphics', 'Rasterization, ray tracing, Phong/Gouraud. VR replaces, AR overlays.'],
      ['E-commerce', 'TLS, PKI, association rules, clustering, recommenders, CDNs.'],
      ['AI', 'Supervised / unsupervised / reinforcement. CNN, RNN, transformer. GAN.'],
      ['Ethics', 'Bias, accountability, privacy, digital divide, jobs. Guidelines, law, education, diverse voices.'],
    ] } },
    { t: 'recap', h: 'You’re ready', items: ['Do the **mixed review quiz** next: 25 questions drawn from every episode.', 'Then take the **AU Practice Exam** in Brightspace › Quizzes. Unlimited attempts.', 'Any topic under 50%? Replay that episode in Slow Mode.'], next: 'Nadia turns over the score sheet. Cut to black.' },
  ],
  quiz: [],
  notes: ['Every fact in this review is sourced in its episode’s practice set.', 'Each tap through the mixed quiz pulls a fresh random set of 25.'],
});
