/* ================= ACT II ================= */
EPISODES.push({
  id: 'ep05', act: 2, label: 'Ep 5', title: 'The Machine That Changes Its Mind', topic: 'Programmability and Turing machines', unit: 'Unit 2 · Section 1', video: DRIVE('1-GK0MAaBUOCL06KRFSJDffdV817ksJzt'),
  steps: [
    { t: 'story', lines: [['scene', 'Mr. Gill unlocks a basement lab. An old machine is running a paper tape.'], ['V', 'It only adds numbers. Scrap it.'], ['G', 'Look closer. The tape isn’t feeding it numbers. It’s feeding it instructions.']] },
    { t: 'idea', h: 'Programmability', p: 'A machine is **programmable** when its input controls **which operations it performs**, not only the values it works on.', w: { type: 'compare', cols: [
      { h: 'Not programmable', lines: ['Input: numbers', 'Always does the same thing (add)', 'New job = build a new machine'] },
      { h: 'Programmable', lines: ['Input: **instructions** + data', 'Does whatever the program says', 'New job = feed it a new program'] },
    ] }, hook: 'One machine, any job. That’s the breakthrough.' },
    { t: 'idea', h: 'The history in four cards', p: '', w: { type: 'flip', items: [
      ['Jacquard loom', 'Punch cards controlled weaving patterns.'],
      ['Analytical Engine (1833–1844)', 'Babbage’s design, programmed with **punch cards** borrowed from Jacquard looms.'],
      ['Ada Lovelace (1843)', 'Wrote the first detailed program for it. Recognized as the **first computer programmer**.'],
      ['Manchester machine (1948)', 'First to store the **program itself as data** (stored program).'],
    ] }, hook: 'Loom → Babbage → Ada → Manchester 1948.' },
    { t: 'check', q: 'Who is recognized as the first computer programmer?', o: ['Charles Babbage', 'Alan Turing', 'Ada Lovelace', 'Grace Hopper'], a: 2 },
    { t: 'idea', h: 'Evans’ model of any computer', p: 'A computer **accepts input, executes a mechanical procedure, and produces output**. Turing turned that into a precise machine.' },
    { t: 'idea', h: 'The Turing machine, piece by piece', p: '', w: { type: 'flip', items: [
      ['Tape', '**Infinite**, split into squares. Used for input, working storage and output.'],
      ['Head', 'Reads one square, writes, then moves **left, right, or halts**.'],
      ['States', 'A **finite** number. Turing said finite because a human can only keep so much in mind.'],
      ['Rules', '(symbol read, current state) → (symbol to write, direction, next state).'],
    ] }, hook: 'Tape, Head, States, Rules: "THe Story Repeats".' },
    { t: 'idea', h: 'Run one yourself', p: 'This machine has one working state, A. It flips every bit and halts on the blank.', w: { type: 'turing', tape: ['0', '1', '1', '_'] } },
    { t: 'check', q: 'Each Turing-machine rule maps (symbol, state) to:', o: ['A new tape', 'A symbol to write, a direction to move, and a new state', 'Only a direction', 'The final output'], a: 1 },
    { t: 'idea', h: 'Why it matters', p: 'Turing (1936) modelled **what a human could do following mechanical rules**. Turing machines can model **any** mechanical computation.' },
    { t: 'recap', items: ['**Programmable** = input controls the operations, not just values.', 'Analytical Engine (punch cards) · Ada Lovelace = first programmer · Manchester 1948 = stored program.', '**Turing machine** = infinite tape + head + **finite** states + rules.', 'Rule: (symbol, state) → (write, move L/R/halt, next state).'], next: 'The tape prints: WIPE SCHEDULED: 72 HOURS.' },
  ],
  quiz: [
    ['Babbage’s Analytical Engine (designed 1833–1844) was programmed using:', ['Magnetic tape', 'Punch cards based on those used by Jacquard looms', 'Vacuum tubes', 'Keyboards'], 1],
    ['Who wrote the first detailed program for the Analytical Engine and is recognized as the first computer programmer?', ['Charles Babbage', 'Alan Turing', 'Ada Lovelace', 'Grace Hopper'], 2],
    ['Programmability means a machine’s inputs can:', ['Only change the values it computes', 'Control the operations it performs, not just the values', 'Change its physical wiring', 'Increase its speed'], 1],
    ['Evans models any computer as a machine that:', ['Accepts input, executes a mechanical procedure, and produces output', 'Stores files and prints them', 'Only performs arithmetic', 'Requires a human operator'], 0],
    ['A Turing machine’s tape is:', ['Finite, read-only', 'Infinite, divided into squares, used for input, working storage, and output', 'A list of instructions only', 'A circular buffer'], 1],
    ['A Turing machine’s number of internal states is:', ['Infinite', 'Finite', 'Always 2', 'Equal to the tape length'], 1],
    ['Each Turing machine rule maps (current symbol, current state) to:', ['A new tape', 'A symbol to write, a direction to move (left, right, or halt), and a new state', 'Only a direction', 'The final output'], 1],
    ['Turing developed his model in 1936 as a model of:', ['Electronic circuits', 'What a human could do following mechanical rules', 'The Internet', 'Babbage’s engine'], 1],
    ['Treating the program itself as data (the stored program) was first implemented by:', ['The Analytical Engine (1840s)', 'The Manchester Small-Scale Experimental Machine (1948)', 'ENIAC (1946)', 'Jacquard’s loom'], 1],
    ['Why did Turing argue the number of machine states must be finite?', ['Memory chips are small', 'A human can only keep a limited amount of information in mind at one time', 'Tapes are short', 'To make it faster'], 1],
  ],
  notes: ['**Study Q2: modelling input, processing, output** (Evans §6.3): input = symbols on the tape; output = what’s on the tape at the end; processing = head + finite state + rules.', '**Study Q1 (why programmability was a breakthrough)** overlaps **A2 Part I**. Write your own explanation and example there.', '**Try it:** design a machine that adds one 1 to the end of a block of 1s. Hint: in state A move right over 1s; on a blank write 1 and halt.'],
});

EPISODES.push({
  id: 'ep05b', act: 2, label: 'Ep 5½', title: 'True or False', topic: 'Boolean logic and gates', unit: 'Unit 1 S2 & Unit 2 S1', video: DRIVE('1e21wioBm2r586-iW5-wRmqoE4VstE8V6'),
  steps: [
    { t: 'story', lines: [['G', 'Before chips, before code, there were only two answers: true and false.'], ['N', 'And you can build a whole computer from that?'], ['G', 'Watch.']] },
    { t: 'idea', h: 'Boolean logic', p: 'Named after **George Boole**. Only **2 values**: true or false (1 or 0). In electronics: **voltage present = true**, **absent = false**.', p2: 'The **digital abstraction**: any value above a threshold counts as true, below counts as false.' },
    { t: 'idea', h: 'Play with the gates', p: 'Flip A and B. Watch which lamps light up.', w: { type: 'gates' } },
    { t: 'idea', h: 'The rules in one line each', p: '', w: { type: 'flip', items: [
      ['AND', 'True only when **both** are true.'],
      ['OR', 'False only when **both** are false.'],
      ['NOT', 'Flips it. NOT true = false.'],
      ['XOR', 'True when **exactly one** is true.'],
      ['NAND', 'NOT AND. Can build **every** other gate. (nand A A) = NOT A.'],
    ] }, hook: 'XOR = "one or the other, not both".' },
    { t: 'check', q: 'A truth table for a function with **two** inputs needs how many rows?', o: ['2', '3', '4', '8'], a: 2, why: '2 inputs × 2 values each = 2² = 4 rows: 00, 01, 10, 11.' },
    { t: 'idea', h: 'Adding numbers with gates', p: 'Adding two 1-bit numbers A + B gives a **sum bit** and a **carry bit**: **sum = XOR**, **carry = AND**.', p2: 'Try A = 1, B = 1 in the gates above: carry 1, sum 0 → binary **10** = 2.', hook: 'XOR sums, AND carries.' },
    { t: 'idea', h: 'Composing operations', p: 'Bigger logic is built by feeding gate outputs into other gates. A three-input AND is **(and (and A B) C)**. Same "composition" idea as procedures in Evans §4.2.' },
    { t: 'check', q: 'Which single gate can build **every** Boolean function?', o: ['AND', 'OR', 'NAND', 'XOR'], a: 2 },
    { t: 'recap', items: ['Boolean = **2 values**, named after **George Boole**.', 'AND both · OR either · NOT flips · XOR exactly one · **NAND builds everything**.', 'Truth table with 2 inputs = **4 rows**.', 'Half adder: **sum = XOR, carry = AND**. 3-input AND = (and (and A B) C).'] },
  ],
  quiz: [
    ['Boolean logic has how many possible values?', ['1', '2 (true / false)', '10', 'Unlimited'], 1],
    ['Boolean logic is named after:', ['George Boole', 'Alan Turing', 'Charles Babbage', 'John Backus'], 0],
    ['A truth table for a function with two inputs needs how many rows?', ['2', '3', '4', '8'], 2],
    ['(A AND B) is true when:', ['Either input is true', 'Both inputs are true', 'Both inputs are false', 'The inputs differ'], 1],
    ['(A OR B) is false only when:', ['Both inputs are false', 'Both are true', 'A is true', 'Never'], 0],
    ['(NOT A) when A is true gives:', ['True', 'False', 'Undefined', 'A'], 1],
    ['XOR (exclusive or) is true when:', ['Both inputs are true', 'Exactly one input is true', 'Both are false', 'Always'], 1],
    ['The digital abstraction means:', ['Using only digital cameras', 'Treating any value above a threshold as true and below it as false', 'Storing data in decimals', 'Removing all physics'], 1],
    ['Which single gate can be used to build every Boolean logic function?', ['AND', 'OR', 'NAND', 'XOR'], 2],
    ['Using only NAND, (NOT A) can be written as:', ['(nand A B)', '(nand A A)', '(nand (not A) B)', '(and A A)'], 1],
    ['Adding two one-bit numbers, the **sum** bit is ___ and the **carry** bit is ___.', ['AND; OR', 'XOR; AND', 'OR; XOR', 'NOT; AND'], 1],
    ['A three-input AND can be built from two-input ANDs as:', ['(and A B C D)', '(and (and A B) C)', '(or (and A B) C)', '(not (and A B))'], 1],
  ],
  notes: ['**Try it:** fill in the truth table for (A AND (NOT B)). (00→0, 01→0, 10→1, 11→0.)', 'Evans Exercise 6.4 (XOR using only NAND) is good practice.'],
});

EPISODES.push({
  id: 'ep06', act: 2, label: 'Ep 6', title: 'Seventy-Two Hours', topic: 'Efficiency and Big-O', unit: 'Unit 2 · Section 2', video: DRIVE('1ngALSpvSh-mYchIGnQ9kwMUXOfUHH4r-'),
  steps: [
    { t: 'story', lines: [['scene', 'Two progress bars: Victor’s and Nadia’s. His is winning.'], ['scene', 'Overnight, the archive doubles in size. Victor’s bar slows to a crawl.'], ['V', 'Why is mine stuck?!']] },
    { t: 'idea', h: 'Measure growth, not seconds', p: '**Running time** = the number of **steps** as a function of the **input size n**. What matters is how the step count **grows** when n grows.', p2: 'We analyze the **worst case**: the input of that size that needs the most work. That gives a guarantee.', hook: 'Big-O asks: "What happens when the data gets huge?"' },
    { t: 'idea', h: 'Drag the slider', p: 'Same input, five growth rates. Watch the gap explode.', w: { type: 'growth' } },
    { t: 'idea', h: 'Victor vs Nadia', p: '', w: { type: 'compare', cols: [
      { h: 'Victor: compare every file with every other', lines: ['n(n−1) comparisons', '**Quadratic, Θ(n²)**', 'Data doubles → **4×** slower', '1 million files ≈ **1 trillion** comparisons'] },
      { h: 'Nadia: check each file once', lines: ['n checks', '**Linear, Θ(n)**', 'Data doubles → **2×** slower', '1 million files = 1 million checks'] },
    ] } },
    { t: 'check', q: 'A procedure is Θ(n²). You **double** the input. Time grows about:', o: ['×2', '×3', '×4', 'Stays the same'], a: 2, why: '(2n)² = 4n².' },
    { t: 'idea', h: 'The growth family', p: '', w: { type: 'flip', items: [
      ['O(1) constant', 'Doesn’t grow with the input.'],
      ['Θ(n) linear', 'Double n → double the time.'],
      ['Θ(n²) quadratic', 'Double n → **4×** the time.'],
      ['Θ(2ⁿ) exponential', 'Add **one** item → time doubles. Only feasible for small n.'],
    ] } },
    { t: 'idea', h: 'O, Ω, Θ: three different promises', p: '', w: { type: 'flip', items: [
      ['O(f) "Big-O"', 'Grows **no faster** than f. (upper bound)'],
      ['Ω(f) "Omega"', 'Grows **no slower** than f. (lower bound)'],
      ['Θ(f) "Theta"', 'Grows **at the same rate** as f. (both O and Ω)'],
    ] }, hook: 'O = ceiling. Ω = floor. Θ = both: exactly that rate.' },
    { t: 'idea', h: 'One warning', p: 'Big-O **hides the constants**. For a particular small input, a Θ(n²) procedure can actually be faster than a Θ(n) one. Interpret it cautiously.' },
    { t: 'check', q: 'A procedure whose time **doubles when you add one input item** is:', o: ['Linear', 'Quadratic', 'Exponential, Θ(2ⁿ)', 'Constant'], a: 2 },
    { t: 'recap', items: ['Running time = **steps vs input size**, in the **worst case**.', 'O = no faster · Ω = no slower · Θ = same rate.', 'Double n: O(1) same · O(n) ×2 · O(n²) ×4 · O(2ⁿ) doubles per **extra item**.', 'Constants are hidden, so read Big-O with care.'], next: 'Nadia finishes. But the one record she needs is buried among 10 million names.' },
  ],
  quiz: [
    ['O(f) is the set of functions that:', ['Grow no slower than f', 'Grow no faster than f', 'Grow at exactly the rate of f', 'Never grow'], 1],
    ['Θ(f) is the set of functions that:', ['Grow no faster than f', 'Grow no slower than f', 'Grow at the same rate as f (the intersection of O(f) and Ω(f))', 'Are constant'], 2],
    ['In running-time analysis, the **worst case input** is:', ['The smallest input', 'The input of a given size that takes the most work', 'Random input', 'An invalid input'], 1],
    ['If running time is in Θ(n), doubling the input size will approximately:', ['Keep it the same', 'Double it', 'Quadruple it', 'Square it'], 1],
    ['If running time is in Θ(n²), doubling the input size will approximately:', ['Double it', 'Triple it', 'Quadruple it', 'Leave it unchanged'], 2],
    ['Comparing every element of an n-element list with every other needs n(n−1) comparisons. Its growth is:', ['Θ(1)', 'Θ(n)', 'Θ(n²)', 'Θ(log n)'], 2],
    ['A procedure whose running time doubles when the input size increases by **one** has growth:', ['Linear', 'Quadratic', 'Exponential, Θ(2ⁿ)', 'Constant'], 2],
    ['A constant-time procedure, in O(1):', ['Examines every input element', 'Does not grow as the input grows', 'Doubles with the input', 'Cannot exist'], 1],
    ['Why must asymptotic analysis be "interpreted cautiously"?', ['Big-O is always wrong', 'Constants are hidden, so for a given input size a Θ(n²) procedure may be faster than a Θ(n) one', 'Computers are too fast to measure', 'It only applies to sorting'], 1],
    ['Roughly how many comparisons does comparing every pair among 1,000,000 files need?', ['About 1 million', 'About 2 million', 'About 1 trillion (10¹²)', 'About 1 billion'], 2],
  ],
  notes: ['**Try it:** 4 seconds on 1,000 items. On 2,000 items: Θ(n) → 8 s; Θ(n²) → 16 s; O(1) → 4 s.', '**Worst case example:** a linear search is worst when the item is missing.', '**Discussion spark:** when might the asymptotically slower method be the better practical choice?'],
});

EPISODES.push({
  id: 'ep07', act: 2, label: 'Ep 7', title: 'Divide and Conquer', topic: 'Searching, sorting, binary trees', unit: 'Unit 2 · Section 3', video: DRIVE('1B8Cc5NrhTLe1nqzLds9uw12RzmPXismt'),
  steps: [
    { t: 'story', lines: [['A', 'Ten million names. Thirty seconds.'], ['T', 'I’ll start scrolling…'], ['N', 'Remember Ep 2? Halve the pile.']] },
    { t: 'idea', h: 'Binary search', p: 'Check the **middle**. Throw away the half that can’t contain it. Repeat.', w: { type: 'bsearch' }, hook: 'Same trick as the 10 questions in Ep 2.' },
    { t: 'idea', h: 'How fast is it?', p: 'Binary search is **Θ(log n)**. Doubling the data adds only **one more step**. 10,000,000 names → about **24** halvings.', p2: 'Unstructured (linear) search must check **every element** in the worst case, which is when the item isn’t there at all.' },
    { t: 'check', q: 'What is the **big limitation** of binary search?', o: ['It only works on numbers', 'It only works if the data is already sorted', 'It needs a GPU', 'It is always slower than linear search'], a: 1, why: 'Victor shuffled the list to break it. Nadia had to sort first.' },
    { t: 'idea', h: 'Sorted binary tree', p: 'Another way to keep data searchable: everything **smaller goes left**, everything **bigger goes right**, at every node.', w: { type: 'bst' }, hook: 'Small left, big right. Every time.' },
    { t: 'idea', h: 'Why a tree is recursive', p: 'Evans: "A Tree is either **null**, or a triple whose first and third parts are **both Trees**." Every left and right side is itself a tree, so tree procedures recurse left or right.', p2: 'Search a sorted tree: null → not here (base case); match → done; otherwise go left or right only. On a balanced tree: **Θ(log n)**.' },
    { t: 'idea', h: 'Sorting speeds', p: '', w: { type: 'flip', items: [
      ['Insertion sort', 'Θ(n²)'],
      ['Quicksort (expected)', 'Θ(n log n)'],
      ['Quicksort (worst case)', 'Θ(n²)'],
      ['Tree sort (expected)', 'Θ(n log n)'],
    ] }, hook: 'Quicksort: quick on average, n² on a bad day.' },
    { t: 'check', q: 'In a sorted binary tree, the left subtree of a node holds values that are:', o: ['Larger', 'Smaller', 'Random', 'Equal'], a: 1 },
    { t: 'recap', items: ['Linear search: Θ(n), worst case = item missing.', '**Binary search: Θ(log n), ONLY on sorted data.** Double n → +1 step.', 'Sorted binary tree: small left, big right; it’s recursive.', 'Insertion sort Θ(n²) · quicksort Θ(n log n) expected, Θ(n²) worst.'], next: 'The record names the buyer: HALCYON. It’s written in code Nadia can’t read.' },
  ],
  quiz: [
    ['Searching **unstructured** data for an item requires, in the worst case:', ['One check', 'About log₂ n checks', 'Checking every element (linear)', 'n² checks'], 2],
    ['The worst case for an unstructured (linear) search is when:', ['The item is first', 'The item is in the middle', 'No element matches', 'The list is sorted'], 2],
    ['On a well-balanced sorted binary tree, binary search runs in:', ['Θ(1)', 'Θ(log n)', 'Θ(n)', 'Θ(n²)'], 1],
    ['With binary search, doubling the number of elements increases search time by:', ['Double', 'Four times', 'Only a constant (about one more step)', 'Nothing'], 2],
    ['The main limitation of binary search is that:', ['It only works on numbers', 'It only works if the data is already sorted', 'It needs a GPU', 'It is always slower than linear search'], 1],
    ['In a sorted binary tree, elements in the left subtree of a node are:', ['Larger', 'Smaller', 'Random', 'Equal'], 1],
    ['A binary tree is a **recursive** data structure because:', ['It is drawn upside down', 'Its left and right sides are themselves trees', 'It contains loops', 'It uses recursion to print'], 1],
    ['Insertion sort’s running time is in:', ['Θ(log n)', 'Θ(n)', 'Θ(n log n)', 'Θ(n²)'], 3],
    ['Quicksort’s **expected** running time is in:', ['Θ(n)', 'Θ(n log n)', 'Θ(n²)', 'Θ(2ⁿ)'], 1],
    ['Quicksort’s **worst case** running time is in:', ['Θ(log n)', 'Θ(n log n)', 'Θ(n²)', 'Θ(1)'], 2],
    ['About how many halvings does it take to narrow 10,000,000 sorted items down to one?', ['10', '24', '1,000', '5,000,000'], 1, '⌈log₂ 10⁷⌉ = 24.'],
  ],
  notes: ['**Build a sorted tree recursively** (Evans tree-insert-one): inserting into null makes a new node (base case); otherwise compare with the root and insert left or right.', '**Try it:** insert 50, 30, 70, 20, 40, 60, 80. Search for 60: 50 → 70 → 60.', '**A2 Part II and A4 Part I** ask for binary-search pseudocode and Python on a specific array. Write those yourself.'],
});

/* ================= ACT III ================= */
EPISODES.push({
  id: 'ep08', act: 3, label: 'Ep 8', title: 'How vs What', topic: 'Imperative vs declarative programming', unit: 'Unit 3 · Section 1', video: DRIVE('1BkJtV9JxSKPwORSZX12rGsCgSyn04A2a'),
  steps: [
    { t: 'story', lines: [['scene', 'Two coders, one deadline. Victor’s team writes 200 lines. Nadia writes one.'], ['scene', 'Victor’s loop quietly changes a shared `balance` variable. The audit fails.']] },
    { t: 'idea', h: 'Two ways to tell a computer what to do', p: '', w: { type: 'compare', cols: [
      { h: 'Imperative: HOW', code: 'total = 0\nfor n in nums:\n    if n % 2 == 0:\n        total += n * n\nprint(total)' },
      { h: 'Declarative: WHAT', code: 'SELECT SUM(n*n)\nFROM nums\nWHERE n % 2 = 0;' },
    ] }, hook: 'Imperative = a recipe. Declarative = an order at a restaurant.' },
    { t: 'idea', h: 'The key differences', p: '', w: { type: 'flip', items: [
      ['Focus', 'Imperative: **how**. Declarative: **what**.'],
      ['State', 'Imperative: **mutable** (variables change). Declarative: immutable, **pure functions**.'],
      ['Side effects', 'Imperative: possible. Declarative: avoided.'],
      ['Examples', 'Imperative: C, Java, Python. Declarative: **SQL, Prolog, Haskell**.'],
    ] } },
    { t: 'idea', h: 'Pure functions and side effects', p: 'A **pure function** always gives the same output for the same input and **changes nothing outside itself**. A **side effect** is any change to program state beyond the return value, like Victor’s loop changing `balance`.', hook: 'Pure = no fingerprints left behind.' },
    { t: 'check', q: 'Which of these is a **declarative** language?', o: ['C', 'Assembler', 'SQL', 'COBOL'], a: 2 },
    { t: 'idea', h: 'Nadia’s one line', p: 'Functional style: filter → map → reduce. Step through it.', w: { type: 'steps', frames: [
      { html: '<div class="chips"><span class="chip">1</span><span class="chip">2</span><span class="chip">3</span><span class="chip">4</span><span class="chip">5</span><span class="chip">6</span></div>', cap: 'Start: [1, 2, 3, 4, 5, 6]' },
      { html: '<div class="chips"><span class="chip dim">1</span><span class="chip acc">2</span><span class="chip dim">3</span><span class="chip acc">4</span><span class="chip dim">5</span><span class="chip acc">6</span></div>', cap: '**filter**: keep the even numbers → [2, 4, 6]' },
      { html: '<div class="chips"><span class="chip acc">4</span><span class="chip acc">16</span><span class="chip acc">36</span></div>', cap: '**map**: square each one → [4, 16, 36]' },
      { html: '<div class="bigstat">56</div>', cap: '**reduce**: add them up → 4 + 16 + 36 = **56**. No variable was changed along the way.' },
    ] } },
    { t: 'idea', h: 'The paradigm family', p: '', w: { type: 'flip', items: [
      ['Logic (Prolog)', '**Predicates, facts and rules**, with logical inference.'],
      ['Functional (Haskell)', 'Pure functions, recursion, higher-order functions, immutability. Based on **lambda calculus**.'],
      ['Modular', 'Program split into **independent, reusable, replaceable modules**.'],
      ['Python', '**Multi-paradigm**: procedural, object-oriented, and partly functional.'],
    ] }, hook: 'Prolog = logic. Haskell = functional. C = imperative.' },
    { t: 'check', q: 'The theoretical foundation of functional programming is:', o: ['Turing machines', 'Lambda calculus', 'Relational algebra', 'Boolean logic only'], a: 1 },
    { t: 'recap', items: ['**Imperative** = HOW: steps, loops, mutable state, side effects possible.', '**Declarative** = WHAT: SQL, Prolog (logic), Haskell (functional).', '**Pure function** = same in → same out, no outside changes.', 'Functional is based on **lambda calculus**. **Python is multi-paradigm.**'], next: 'The side effect wasn’t an accident. Someone edited the code at 3:12 a.m.' },
  ],
  quiz: [
    ['Imperative programming focuses on:', ['What the result is', 'How to achieve the result, with explicit steps that change state', 'Logical predicates only', 'Markup'], 1],
    ['Declarative programming focuses on:', ['Explicit loops', 'What the desired result is, leaving how to the system', 'Memory addresses', 'Hardware control'], 1],
    ['Which is a declarative language?', ['C', 'Assembler', 'SQL', 'COBOL'], 2],
    ['A **pure function**:', ['Changes global variables', 'Always produces the same output for the same input and does not modify external state', 'Has no parameters', 'Only prints'], 1],
    ['A **side effect** is:', ['A syntax error', 'A change to program state outside a function’s return value', 'A comment', 'A type of loop'], 1],
    ['Logic programming (e.g. Prolog) is built on:', ['Objects', 'Predicates, facts and rules, with logical inference', 'Pointers', 'GUI events'], 1],
    ['Functional programming (e.g. Haskell) relies heavily on:', ['Mutable state and gotos', 'Pure functions, recursion, higher-order functions, immutability', 'Global variables', 'Inheritance'], 1],
    ['The theoretical foundation of functional programming is:', ['Turing machines', 'Lambda calculus', 'Relational algebra', 'Boolean logic only'], 1],
    ['Python is described by Zhang as:', ['Purely functional', 'Purely object-oriented', 'Multi-paradigm: procedural, object-oriented, and to some extent functional', 'A logic language'], 2],
    ['Which style divides a program into independent, reusable, replaceable modules?', ['Structured', 'Procedural', 'Modular', 'Declarative'], 2],
    ['Using functional Python, the sum of the squares of the even numbers in [1, 2, 3, 4, 5, 6] is:', ['20', '56', '91', '12'], 1, '4 + 16 + 36 = 56.'],
  ],
  notes: ['**Python’s multi-paradigm features** (R2 p 6): functions; classes, inheritance, polymorphism; first-class functions, lambda, map, filter, reduce.', '**Procedural vs modular pseudocode:** study Zhang Appendix 1. **A3 Part I** asks for your own scenario, so don’t reuse Zhang’s grading example.', '**Try it:** write a SQL query and an imperative loop that both count payments over $500. Point out the mutable variable in the loop.'],
});

EPISODES.push({
  id: 'ep09', act: 3, label: 'Ep 9', title: 'Override', topic: 'Objects, inheritance, overriding', unit: 'Unit 3 · Section 2', video: DRIVE('1LsRv26IJ8IDMLhuRk-2-wWRmqcE_UNyQ'),
  steps: [
    { t: 'story', lines: [['scene', 'Her father’s code: `class Founder`, `class Heir(Founder)`. Victor’s commit adds `class Acting(Heir)`.'], ['scene', 'Everyone calls `decide()`. Victor’s object says "SELL ORACLE".'], ['N', 'Same call, different answer. How?']] },
    { t: 'idea', h: 'Class vs object', p: 'A **class** is the blueprint. An **object** (instance) is one thing built from it. Its stored data are **instance variables**. A **constructor** creates new objects.', p2: 'You **invoke** a method by sending the object a **message**: `nadia.decide()`.', hook: 'Class = cookie cutter. Object = cookie.' },
    { t: 'idea', h: 'Trace the call yourself', p: 'Python starts at the object’s own class and **climbs up** until it finds the method.', w: { type: 'dispatch' } },
    { t: 'idea', h: 'Inherit vs override', p: '', w: { type: 'flip', items: [
      ['Inherit', 'Subclass doesn’t define the method → it uses the **superclass’s** version. (`vote()` for everyone.)'],
      ['Override', 'Subclass defines its **own** version that replaces the parent’s. (Acting’s `decide()`.)'],
      ['Dynamic dispatch', '**The method that runs depends on the object’s class.** Same call, different result.'],
    ] }, hook: 'Override = Victor writing over Dad’s decision.' },
    { t: 'check', q: 'A subclass does **not** define `vote()`. Calling `vote()` on it:', o: ['Raises an error', 'Uses the superclass’s definition', 'Returns null', 'Creates a new method'], a: 1 },
    { t: 'idea', h: 'More OOP words', p: '', w: { type: 'flip', items: [
      ['Encapsulation', 'Keep the object’s state inside it; change it only through its methods.'],
      ['Observer method', 'Reports state **without changing** it.'],
      ['Mutator method', 'Changes the state.'],
      ['One superclass', 'In Evans’ system a class can have many subclasses but only **one** superclass.'],
    ] } },
    { t: 'check', q: '`class Heir(Founder)` and `class Acting(Heir)`. `isinstance(Acting("V"), Founder)` is:', o: ['True', 'False', 'An error', 'None'], a: 0, why: 'Acting is an Heir, and an Heir is a Founder. So it’s True all the way up.' },
    { t: 'recap', items: ['**Class** = blueprint; **object** = instance; **instance variables** = its data; **constructor** = makes it.', 'Invoke = send the object a **message**.', '**Inherit** = use the parent’s method. **Override** = replace it.', '**Dynamic dispatch**: the method run depends on the object.', '**Encapsulation** hides state behind methods.'], next: 'An override comment is signed with Theo’s initials.' },
  ],
  quiz: [
    ['The state variables that are part of an object are called:', ['Parameters', 'Instance variables', 'Constants', 'Tokens'], 1],
    ['Procedures that create new objects of a class are called:', ['Destructors', 'Constructors', 'Observers', 'Mutators'], 1],
    ['In Evans’ terms, we **invoke** a method on an object by:', ['Compiling it', 'Sending the object a message', 'Deleting it', 'Copying it'], 1],
    ['If a subclass does not define a method, invoking it on a subclass object:', ['Raises an error', 'Uses the superclass’s definition', 'Returns null', 'Creates a new method'], 1],
    ['When a subclass replaces a method defined by its superclass, the subclass method:', ['Overloads it', 'Overrides it', 'Hides the class', 'Deletes the superclass'], 1],
    ['"The method invoked depends on the object" describes:', ['Encapsulation', 'Dynamic dispatch', 'Recursion', 'Compilation'], 1],
    ['Keeping an object’s state inside it, manipulated only through its methods, is:', ['Inheritance', 'Encapsulation', 'Polymorphism', 'Lambda'], 1],
    ['In Evans’ object system, a class can have many subclasses but only:', ['One instance', 'One superclass', 'One method', 'One constructor'], 1],
    ['Methods that report an object’s state without changing it are called:', ['Mutators', 'Observers', 'Constructors', 'Overrides'], 1],
    ['Given `class Acting(Heir)` and `class Heir(Founder)`, `isinstance(Acting("V"), Founder)` is:', ['True', 'False', 'An error', 'None'], 0],
  ],
  notes: ['**Hierarchy diagram:** arrows go **from each subclass to its superclass** (Evans Fig 10.2): Founder ← Heir ← Acting.', '**Verify runtime status:** make one instance per class, print `type(obj).__name__` and `isinstance(obj, Founder)`, invoke each method and note which class answered. **A3 Part I/II** ask similar things with C1–C4: do those yourself.', '**Try it:** Vehicle.wheels() → 4; Bike(Vehicle) overrides → 2; EBike(Bike) adds battery(). EBike().wheels()? (2.)'],
});

EPISODES.push({
  id: 'ep10', act: 3, label: 'Ep 10', title: 'It Compiled. It’s Still Wrong.', topic: 'Interpreters, compilers, precedence', unit: 'Unit 3 · Section 3', video: DRIVE('1Acmvm1MwRJha9mg1SonXj-tGoR0rUmET'),
  steps: [
    { t: 'story', lines: [['O', 'The build passed. So why does the report say our average sale is $1,050?'], ['V', 'Because Nadia’s team is cooking the numbers.'], ['G', 'Or because nobody read the formula.']] },
    { t: 'idea', h: 'The bug', p: 'The code says `average = a + b / 2` with a = 1000, b = 100. Toggle the parentheses and watch the tree change.', w: { type: 'precedence' }, hook: 'Runs fine ≠ correct.' },
    { t: 'check', q: 'In Python, `3 + 4 * 5` evaluates to:', o: ['35', '23', '27', '12'], a: 1, why: 'Multiplication first: 4 × 5 = 20, then 3 + 20 = 23.' },
    { t: 'idea', h: 'Inside an interpreter', p: 'Mr. Gill walks through the pipeline. Step through it.', w: { type: 'steps', frames: [
      { html: '<pre class="code">(define square (lambda (x) (* x x)))</pre>', cap: '**Source code**: just a string of characters.' },
      { html: '<div class="chips">' + ['(', 'define', 'square', '(', 'lambda', '(', 'x', ')', '(', '*', 'x', 'x', ')', ')', ')'].map(t => `<span class="chip">${t}</span>`).join('') + '</div>', cap: '**Tokenizer** splits it into **tokens**, the smallest meaningful pieces. Count them: **15**.' },
      { html: '<pre class="code">define\n ├─ square\n └─ lambda\n     ├─ (x)\n     └─ *\n         ├─ x\n         └─ x</pre>', cap: '**Parser** arranges the tokens by the grammar into a **parse tree**.' },
      { html: '<div class="bigstat">square → a procedure</div>', cap: '**Evaluator** walks the tree with an **environment** (names → values) and produces a value.' },
    ] }, hook: 'Tokenize → Parse → Evaluate. "Take Pictures Everywhere".' },
    { t: 'idea', h: 'Compiler vs interpreter', p: '', w: { type: 'compare', cols: [
      { h: 'Compiler', lines: ['Translates the **whole program first** into machine-level code', 'Runs later, usually **faster**', 'Can catch some mistakes **before** running'] },
      { h: 'Interpreter', lines: ['Translates and runs **a small piece at a time**', 'Usually **slower**', 'Easy to change and try again'] },
    ] }, hook: 'Compiler = translate the whole book. Interpreter = live translator, sentence by sentence.' },
    { t: 'idea', h: 'Who built the first compilers?', p: '**Grace Hopper**, in the 1950s.' },
    { t: 'check', q: 'The parser’s job is to:', o: ['Compute values', 'Structure tokens according to the grammar (e.g. into a tree)', 'Store files', 'Encrypt the code'], a: 1 },
    { t: 'recap', items: ['**Compiler**: translate all first, run later. **Interpreter**: piece by piece while running (slower).', 'Pipeline: **tokenizer → parser → evaluator**. Token = indivisible unit.', 'First compilers: **Grace Hopper**, 1950s.', 'Compiles/runs ≠ correct. Precedence: `1000 + 100/2 = 1050`, `(1000+100)/2 = 550`.'], next: 'Theo is caught copying ORACLE onto a USB stick.' },
  ],
  quiz: [
    ['A compiler:', ['Runs the program one line at a time', 'Translates an entire program at once into a machine-level program', 'Only checks spelling', 'Is a type of database'], 1],
    ['An interpreter:', ['Produces a separate machine-language file first', 'Translates and executes the program a small piece at a time while it runs', 'Cannot run Python', 'Is always faster than a compiler'], 1],
    ['One disadvantage of interpreting compared to compiling is that the program:', ['Cannot be changed', 'Usually runs slower', 'Cannot have errors', 'Needs no input'], 1],
    ['An advantage of compilers is that, because they translate the whole program, they can:', ['Skip testing', 'Analyze it and detect some mistakes before it runs', 'Guarantee no bugs', 'Run without hardware'], 1],
    ['Who developed the first compilers in the 1950s?', ['Alan Turing', 'Ada Lovelace', 'Grace Hopper', 'Tim Berners-Lee'], 2],
    ['The first stage of Evans’ Charme interpreter, which splits a program string into tokens, is the:', ['Evaluator', 'Tokenizer', 'Linker', 'Printer'], 1],
    ['A token is:', ['A password', 'An indivisible syntactic unit', 'A full statement', 'A comment'], 1],
    ['How many tokens are in `(define square (lambda (x) (* x x)))`?', ['7', '11', '15', '20'], 2],
    ['In Python, `3 + 4 * 5` evaluates to:', ['35', '23', '27', '12'], 1],
    ['The parser’s job is to:', ['Compute values', 'Structure tokens according to the program’s grammar (for example into a tree)', 'Store files', 'Encrypt the code'], 1],
    ['A program that compiles or runs without errors:', ['Is always correct', 'Can still give wrong results if its logic (such as operator precedence) is wrong', 'Cannot be changed', 'Must be declarative'], 1],
  ],
  notes: ['**Try it:** predict, then check in Python: `10 - 4 - 2` (4), `10 - (4 - 2)` (8), `2 ** 3 ** 2` (512, because ** groups right to left).', '**A3 Part III** asks you to compile, test and fix GoodDocsF.cpp. Use the program’s own documented formulas and do it yourself.', '**Discussion spark:** when would you still prefer a compiler?'],
});
